name: Build with shellcheck

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0

      - run: sudo apt install shellcheck pandoc dpkg-dev
      - run: ./scripts/shellcheck.sh
      - run: ./scripts/build-deb.sh

      - uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9  # v7.0.2
        with:
          name: deliverables
          path: |
            ./*.deb
            ./*.deb.*sum
      - uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9  # v7.0.2
        with:
          name: target
          path: ./target/
